# Generated by Django 4.2.7 on 2023-12-26 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Mingle', '0006_alter_chat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat_Mingle.userprofile'),
        ),
    ]
