# Generated by Django 4.2.7 on 2023-12-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Mingle', '0009_remove_chat_user_profile_alter_chat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, to='Chat_Mingle.group'),
        ),
    ]
